# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageViewer.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageViewer(object):
    def setupUi(self, ImageViewer):
        ImageViewer.setObjectName("ImageViewer")
        ImageViewer.resize(1335, 961)
        self.Imageviewer = QtWidgets.QWidget(ImageViewer)
        self.Imageviewer.setObjectName("Imageviewer")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.Imageviewer)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.scrollArea = QtWidgets.QScrollArea(self.Imageviewer)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1311, 886))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.Wholeframe = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.Wholeframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Wholeframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Wholeframe.setObjectName("Wholeframe")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.Wholeframe)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.Wholelayout = QtWidgets.QHBoxLayout()
        self.Wholelayout.setObjectName("Wholelayout")
        self.Inputsframe = QtWidgets.QFrame(self.Wholeframe)
        self.Inputsframe.setMinimumSize(QtCore.QSize(500, 0))
        self.Inputsframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Inputsframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Inputsframe.setObjectName("Inputsframe")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.Inputsframe)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.Inputslayout = QtWidgets.QVBoxLayout()
        self.Inputslayout.setObjectName("Inputslayout")
        self.AllInput1frame = QtWidgets.QFrame(self.Inputsframe)
        self.AllInput1frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AllInput1frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AllInput1frame.setObjectName("AllInput1frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.AllInput1frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.AllInput1 = QtWidgets.QVBoxLayout()
        self.AllInput1.setObjectName("AllInput1")
        self.Control1frame = QtWidgets.QFrame(self.AllInput1frame)
        self.Control1frame.setMinimumSize(QtCore.QSize(300, 50))
        self.Control1frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Control1frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Control1frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Control1frame.setObjectName("Control1frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Control1frame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Control1layout = QtWidgets.QHBoxLayout()
        self.Control1layout.setObjectName("Control1layout")
        self.imageone = QtWidgets.QLabel(self.Control1frame)
        self.imageone.setObjectName("imageone")
        self.Control1layout.addWidget(self.imageone)
        self.choose1 = QtWidgets.QComboBox(self.Control1frame)
        self.choose1.setObjectName("choose1")
        self.choose1.addItem("")
        self.choose1.addItem("")
        self.choose1.addItem("")
        self.choose1.addItem("")
        self.Control1layout.addWidget(self.choose1)
        self.gridLayout_7.addLayout(self.Control1layout, 0, 0, 1, 1)
        self.AllInput1.addWidget(self.Control1frame)
        self.Input1frame = QtWidgets.QFrame(self.AllInput1frame)
        self.Input1frame.setMinimumSize(QtCore.QSize(400, 150))
        self.Input1frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Input1frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Input1frame.setObjectName("Input1frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.Input1frame)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Input1 = QtWidgets.QHBoxLayout()
        self.Input1.setObjectName("Input1")
        self.Image1layout = QtWidgets.QVBoxLayout()
        self.Image1layout.setObjectName("Image1layout")
        self.Image1 = ImageView(self.Input1frame)
        self.Image1.setObjectName("Image1")
        self.Image1layout.addWidget(self.Image1)
        self.Input1.addLayout(self.Image1layout)
        self.EditImage1layout = QtWidgets.QVBoxLayout()
        self.EditImage1layout.setObjectName("EditImage1layout")
        self.EditImage1 = ImageView(self.Input1frame)
        self.EditImage1.setObjectName("EditImage1")
        self.EditImage1layout.addWidget(self.EditImage1)
        self.Input1.addLayout(self.EditImage1layout)
        self.gridLayout_8.addLayout(self.Input1, 0, 0, 1, 1)
        self.AllInput1.addWidget(self.Input1frame)
        self.gridLayout_6.addLayout(self.AllInput1, 0, 0, 1, 1)
        self.Inputslayout.addWidget(self.AllInput1frame)
        self.AllInput2frame = QtWidgets.QFrame(self.Inputsframe)
        self.AllInput2frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AllInput2frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AllInput2frame.setObjectName("AllInput2frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.AllInput2frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.AllInput2 = QtWidgets.QVBoxLayout()
        self.AllInput2.setObjectName("AllInput2")
        self.Control2frame = QtWidgets.QFrame(self.AllInput2frame)
        self.Control2frame.setMinimumSize(QtCore.QSize(300, 50))
        self.Control2frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Control2frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Control2frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Control2frame.setObjectName("Control2frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Control2frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Control2layout = QtWidgets.QHBoxLayout()
        self.Control2layout.setObjectName("Control2layout")
        self.imagetwo = QtWidgets.QLabel(self.Control2frame)
        self.imagetwo.setObjectName("imagetwo")
        self.Control2layout.addWidget(self.imagetwo)
        self.choose2 = QtWidgets.QComboBox(self.Control2frame)
        self.choose2.setObjectName("choose2")
        self.choose2.addItem("")
        self.choose2.addItem("")
        self.choose2.addItem("")
        self.choose2.addItem("")
        self.Control2layout.addWidget(self.choose2)
        self.gridLayout_3.addLayout(self.Control2layout, 0, 0, 1, 1)
        self.AllInput2.addWidget(self.Control2frame)
        self.Input2frame = QtWidgets.QFrame(self.AllInput2frame)
        self.Input2frame.setMinimumSize(QtCore.QSize(400, 150))
        self.Input2frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Input2frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Input2frame.setObjectName("Input2frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Input2frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Input2 = QtWidgets.QHBoxLayout()
        self.Input2.setObjectName("Input2")
        self.Image2layout = QtWidgets.QVBoxLayout()
        self.Image2layout.setObjectName("Image2layout")
        self.Image2 = ImageView(self.Input2frame)
        self.Image2.setObjectName("Image2")
        self.Image2layout.addWidget(self.Image2)
        self.Input2.addLayout(self.Image2layout)
        self.EditImage2layout = QtWidgets.QVBoxLayout()
        self.EditImage2layout.setObjectName("EditImage2layout")
        self.EditImage2 = ImageView(self.Input2frame)
        self.EditImage2.setObjectName("EditImage2")
        self.EditImage2layout.addWidget(self.EditImage2)
        self.Input2.addLayout(self.EditImage2layout)
        self.gridLayout_2.addLayout(self.Input2, 0, 0, 1, 1)
        self.AllInput2.addWidget(self.Input2frame)
        self.gridLayout_5.addLayout(self.AllInput2, 0, 0, 1, 1)
        self.Inputslayout.addWidget(self.AllInput2frame)
        self.gridLayout_15.addLayout(self.Inputslayout, 0, 0, 1, 1)
        self.Wholelayout.addWidget(self.Inputsframe)
        self.Resultsframe = QtWidgets.QFrame(self.Wholeframe)
        self.Resultsframe.setMinimumSize(QtCore.QSize(500, 0))
        self.Resultsframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Resultsframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Resultsframe.setObjectName("Resultsframe")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.Resultsframe)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.Resultslayout = QtWidgets.QVBoxLayout()
        self.Resultslayout.setObjectName("Resultslayout")
        self.Mixerframe = QtWidgets.QFrame(self.Resultsframe)
        self.Mixerframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Mixerframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Mixerframe.setObjectName("Mixerframe")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.Mixerframe)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.Mixerlayout = QtWidgets.QVBoxLayout()
        self.Mixerlayout.setObjectName("Mixerlayout")
        self.MixerOutputframe = QtWidgets.QFrame(self.Mixerframe)
        self.MixerOutputframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MixerOutputframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MixerOutputframe.setObjectName("MixerOutputframe")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MixerOutputframe)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mixeroutput = QtWidgets.QLabel(self.MixerOutputframe)
        self.mixeroutput.setObjectName("mixeroutput")
        self.horizontalLayout.addWidget(self.mixeroutput)
        self.choosemixeroutput = QtWidgets.QComboBox(self.MixerOutputframe)
        self.choosemixeroutput.setObjectName("choosemixeroutput")
        self.choosemixeroutput.addItem("")
        self.choosemixeroutput.addItem("")
        self.horizontalLayout.addWidget(self.choosemixeroutput)
        self.Mixerlayout.addWidget(self.MixerOutputframe)
        self.Mcontrol1frame = QtWidgets.QFrame(self.Mixerframe)
        self.Mcontrol1frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Mcontrol1frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Mcontrol1frame.setObjectName("Mcontrol1frame")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.Mcontrol1frame)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.Mcontrol1layout = QtWidgets.QHBoxLayout()
        self.Mcontrol1layout.setObjectName("Mcontrol1layout")
        self.Component1frame = QtWidgets.QFrame(self.Mcontrol1frame)
        self.Component1frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Component1frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Component1frame.setObjectName("Component1frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Component1frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Component1layout = QtWidgets.QHBoxLayout()
        self.Component1layout.setObjectName("Component1layout")
        self.Componentone = QtWidgets.QLabel(self.Component1frame)
        self.Componentone.setObjectName("Componentone")
        self.Component1layout.addWidget(self.Componentone)
        self.Mchoose1 = QtWidgets.QComboBox(self.Component1frame)
        self.Mchoose1.setObjectName("Mchoose1")
        self.Mchoose1.addItem("")
        self.Mchoose1.addItem("")
        self.Component1layout.addWidget(self.Mchoose1)
        self.gridLayout_4.addLayout(self.Component1layout, 0, 0, 1, 1)
        self.Mcontrol1layout.addWidget(self.Component1frame)
        self.Percentage1frame = QtWidgets.QFrame(self.Mcontrol1frame)
        self.Percentage1frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Percentage1frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Percentage1frame.setObjectName("Percentage1frame")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.Percentage1frame)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.Percentage1layout = QtWidgets.QVBoxLayout()
        self.Percentage1layout.setObjectName("Percentage1layout")
        self.Slider1 = QtWidgets.QSlider(self.Percentage1frame)
        self.Slider1.setOrientation(QtCore.Qt.Horizontal)
        self.Slider1.setObjectName("Slider1")
        self.Percentage1layout.addWidget(self.Slider1)
        self.Fchoose1 = QtWidgets.QComboBox(self.Percentage1frame)
        self.Fchoose1.setObjectName("Fchoose1")
        self.Fchoose1.addItem("")
        self.Fchoose1.addItem("")
        self.Fchoose1.addItem("")
        self.Fchoose1.addItem("")
        self.Fchoose1.addItem("")
        self.Fchoose1.addItem("")
        self.Percentage1layout.addWidget(self.Fchoose1)
        self.gridLayout_10.addLayout(self.Percentage1layout, 0, 0, 1, 1)
        self.Mcontrol1layout.addWidget(self.Percentage1frame)
        self.gridLayout_18.addLayout(self.Mcontrol1layout, 0, 0, 1, 1)
        self.Mixerlayout.addWidget(self.Mcontrol1frame)
        self.Mcontrol2frame = QtWidgets.QFrame(self.Mixerframe)
        self.Mcontrol2frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Mcontrol2frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Mcontrol2frame.setObjectName("Mcontrol2frame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.Mcontrol2frame)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.Mcontrol2layout = QtWidgets.QHBoxLayout()
        self.Mcontrol2layout.setObjectName("Mcontrol2layout")
        self.Component2frame = QtWidgets.QFrame(self.Mcontrol2frame)
        self.Component2frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Component2frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Component2frame.setObjectName("Component2frame")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.Component2frame)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.Component2layout = QtWidgets.QHBoxLayout()
        self.Component2layout.setObjectName("Component2layout")
        self.Componenttwo = QtWidgets.QLabel(self.Component2frame)
        self.Componenttwo.setObjectName("Componenttwo")
        self.Component2layout.addWidget(self.Componenttwo)
        self.Mchoose2 = QtWidgets.QComboBox(self.Component2frame)
        self.Mchoose2.setObjectName("Mchoose2")
        self.Mchoose2.addItem("")
        self.Mchoose2.addItem("")
        self.Component2layout.addWidget(self.Mchoose2)
        self.gridLayout_16.addLayout(self.Component2layout, 0, 0, 1, 1)
        self.Mcontrol2layout.addWidget(self.Component2frame)
        self.Percentage2frame = QtWidgets.QFrame(self.Mcontrol2frame)
        self.Percentage2frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Percentage2frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Percentage2frame.setObjectName("Percentage2frame")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.Percentage2frame)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.Percentage2layout = QtWidgets.QVBoxLayout()
        self.Percentage2layout.setObjectName("Percentage2layout")
        self.Slider2 = QtWidgets.QSlider(self.Percentage2frame)
        self.Slider2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider2.setObjectName("Slider2")
        self.Percentage2layout.addWidget(self.Slider2)
        self.Fchoose2 = QtWidgets.QComboBox(self.Percentage2frame)
        self.Fchoose2.setObjectName("Fchoose2")
        self.Percentage2layout.addWidget(self.Fchoose2)
        self.gridLayout_17.addLayout(self.Percentage2layout, 0, 1, 1, 1)
        self.Mcontrol2layout.addWidget(self.Percentage2frame)
        self.gridLayout_9.addLayout(self.Mcontrol2layout, 0, 0, 1, 1)
        self.Mixerlayout.addWidget(self.Mcontrol2frame)
        self.gridLayout_26.addLayout(self.Mixerlayout, 2, 1, 1, 1)
        self.Resultslayout.addWidget(self.Mixerframe)
        self.Outputsframe = QtWidgets.QFrame(self.Resultsframe)
        self.Outputsframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Outputsframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Outputsframe.setObjectName("Outputsframe")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.Outputsframe)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.Outputslayout = QtWidgets.QHBoxLayout()
        self.Outputslayout.setObjectName("Outputslayout")
        self.AllOutput1frame = QtWidgets.QFrame(self.Outputsframe)
        self.AllOutput1frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AllOutput1frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AllOutput1frame.setObjectName("AllOutput1frame")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.AllOutput1frame)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.AllOutput1layout = QtWidgets.QVBoxLayout()
        self.AllOutput1layout.setObjectName("AllOutput1layout")
        self.outputone = QtWidgets.QLabel(self.AllOutput1frame)
        self.outputone.setObjectName("outputone")
        self.AllOutput1layout.addWidget(self.outputone)
        self.Output1frame = QtWidgets.QFrame(self.AllOutput1frame)
        self.Output1frame.setMinimumSize(QtCore.QSize(400, 150))
        self.Output1frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Output1frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Output1frame.setObjectName("Output1frame")
        self.gridLayout = QtWidgets.QGridLayout(self.Output1frame)
        self.gridLayout.setObjectName("gridLayout")
        self.Output1layout = QtWidgets.QVBoxLayout()
        self.Output1layout.setObjectName("Output1layout")
        self.Output1 = ImageView(self.Output1frame)
        self.Output1.setObjectName("Output1")
        self.Output1layout.addWidget(self.Output1)
        self.gridLayout.addLayout(self.Output1layout, 0, 0, 1, 1)
        self.AllOutput1layout.addWidget(self.Output1frame)
        self.gridLayout_12.addLayout(self.AllOutput1layout, 0, 0, 1, 1)
        self.Outputslayout.addWidget(self.AllOutput1frame)
        self.AllOutput2frame = QtWidgets.QFrame(self.Outputsframe)
        self.AllOutput2frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AllOutput2frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AllOutput2frame.setObjectName("AllOutput2frame")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.AllOutput2frame)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.AllOutput2layout = QtWidgets.QVBoxLayout()
        self.AllOutput2layout.setObjectName("AllOutput2layout")
        self.Outputtwo = QtWidgets.QLabel(self.AllOutput2frame)
        self.Outputtwo.setObjectName("Outputtwo")
        self.AllOutput2layout.addWidget(self.Outputtwo)
        self.Output2frame = QtWidgets.QFrame(self.AllOutput2frame)
        self.Output2frame.setMinimumSize(QtCore.QSize(400, 150))
        self.Output2frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Output2frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Output2frame.setObjectName("Output2frame")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.Output2frame)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.Output2layout = QtWidgets.QVBoxLayout()
        self.Output2layout.setObjectName("Output2layout")
        self.Output2 = ImageView(self.Output2frame)
        self.Output2.setObjectName("Output2")
        self.Output2layout.addWidget(self.Output2)
        self.gridLayout_14.addLayout(self.Output2layout, 0, 0, 1, 1)
        self.AllOutput2layout.addWidget(self.Output2frame)
        self.gridLayout_13.addLayout(self.AllOutput2layout, 0, 0, 1, 1)
        self.Outputslayout.addWidget(self.AllOutput2frame)
        self.gridLayout_11.addLayout(self.Outputslayout, 0, 0, 1, 1)
        self.Resultslayout.addWidget(self.Outputsframe)
        self.gridLayout_27.addLayout(self.Resultslayout, 0, 0, 1, 1)
        self.Wholelayout.addWidget(self.Resultsframe)
        self.gridLayout_28.addLayout(self.Wholelayout, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.Wholeframe, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_30.addWidget(self.scrollArea, 0, 0, 1, 1)
        ImageViewer.setCentralWidget(self.Imageviewer)
        self.menubar = QtWidgets.QMenuBar(ImageViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1335, 26))
        self.menubar.setObjectName("menubar")
        self.File = QtWidgets.QMenu(self.menubar)
        self.File.setObjectName("File")
        self.Open = QtWidgets.QMenu(self.File)
        self.Open.setObjectName("Open")
        ImageViewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImageViewer)
        self.statusbar.setObjectName("statusbar")
        ImageViewer.setStatusBar(self.statusbar)
        self.Image_1 = QtWidgets.QAction(ImageViewer)
        self.Image_1.setObjectName("Image_1")
        self.Image_2 = QtWidgets.QAction(ImageViewer)
        self.Image_2.setObjectName("Image_2")
        self.Save = QtWidgets.QAction(ImageViewer)
        self.Save.setObjectName("Save")
        self.Open.addAction(self.Image_1)
        self.Open.addAction(self.Image_2)
        self.File.addAction(self.Open.menuAction())
        self.File.addAction(self.Save)
        self.menubar.addAction(self.File.menuAction())

        self.retranslateUi(ImageViewer)
        QtCore.QMetaObject.connectSlotsByName(ImageViewer)

    def retranslateUi(self, ImageViewer):
        _translate = QtCore.QCoreApplication.translate
        ImageViewer.setWindowTitle(_translate("ImageViewer", "MainWindow"))
        self.imageone.setText(_translate("ImageViewer", "Image One"))
        self.choose1.setItemText(0, _translate("ImageViewer", "Phase"))
        self.choose1.setItemText(1, _translate("ImageViewer", "Magnitude"))
        self.choose1.setItemText(2, _translate("ImageViewer", "Imaginary"))
        self.choose1.setItemText(3, _translate("ImageViewer", "Real"))
        self.imagetwo.setText(_translate("ImageViewer", "Image Two"))
        self.choose2.setItemText(0, _translate("ImageViewer", "Phase"))
        self.choose2.setItemText(1, _translate("ImageViewer", "Magnitude"))
        self.choose2.setItemText(2, _translate("ImageViewer", "Imaginary"))
        self.choose2.setItemText(3, _translate("ImageViewer", "Real"))
        self.mixeroutput.setText(_translate("ImageViewer", "Mixer Output"))
        self.choosemixeroutput.setItemText(0, _translate("ImageViewer", "Output 1"))
        self.choosemixeroutput.setItemText(1, _translate("ImageViewer", "Output 2"))
        self.Componentone.setText(_translate("ImageViewer", "Component 1"))
        self.Mchoose1.setItemText(0, _translate("ImageViewer", "Image 1"))
        self.Mchoose1.setItemText(1, _translate("ImageViewer", "Image 2"))
        self.Fchoose1.setItemText(0, _translate("ImageViewer", "Phase"))
        self.Fchoose1.setItemText(1, _translate("ImageViewer", "Magnitude"))
        self.Fchoose1.setItemText(2, _translate("ImageViewer", "Imaginary"))
        self.Fchoose1.setItemText(3, _translate("ImageViewer", "Real"))
        self.Fchoose1.setItemText(4, _translate("ImageViewer", "Uniform Phase"))
        self.Fchoose1.setItemText(5, _translate("ImageViewer", "Uniform Magnitude"))
        self.Componenttwo.setText(_translate("ImageViewer", "Component 2"))
        self.Mchoose2.setItemText(0, _translate("ImageViewer", "Image 1"))
        self.Mchoose2.setItemText(1, _translate("ImageViewer", "Image 2"))
        self.outputone.setText(_translate("ImageViewer", "Output One"))
        self.Outputtwo.setText(_translate("ImageViewer", "Output Two"))
        self.File.setTitle(_translate("ImageViewer", "File"))
        self.Open.setTitle(_translate("ImageViewer", "Open"))
        self.Image_1.setText(_translate("ImageViewer", "Image 1"))
        self.Image_2.setText(_translate("ImageViewer", "Image 2"))
        self.Save.setText(_translate("ImageViewer", "Save"))
from pyqtgraph import ImageView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImageViewer = QtWidgets.QMainWindow()
    ui = Ui_ImageViewer()
    ui.setupUi(ImageViewer)
    ImageViewer.show()
    sys.exit(app.exec_())
